In [12]:
import os
import tensorflow as tf

In [13]:
os.chdir(r'C:\Users\Niko\OneDrive\שולחן העבודה\csvc')

In [14]:
os.listdir()

['1.csv', '2.csv', '3.csv']

In [20]:
ds = tf.data.experimental.make_csv_dataset(['1.csv', '3.csv'], 1)

In [21]:
for j in ds.take(6):
    print(j)

OrderedDict([('A', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>), ('B', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>), ('C', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>), ('D', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>)])
OrderedDict([('A', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>), ('B', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>), ('C', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>), ('D', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([5])>)])
OrderedDict([('A', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>), ('B', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>), ('C', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>), ('D', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>)])
OrderedDict([('A', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>), ('B', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>), ('C', <tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>), 

In [19]:
@tf.function
def make_features_labels_tuple(x):
    labels = {k: x[k] for k in x if k in label_cols}
    features = {k: x[k] for k in x if k in feature_cols}
    return (features, labels)

In [7]:
label_cols=['C','D']
feature_cols=['A','B']

In [8]:
ds1=ds.map(make_features_labels_tuple)

In [9]:
ds1.take(1)

<TakeDataset shapes: ({A: (1,), B: (1,)}, {C: (1,), D: (1,)}), types: ({A: tf.int32, B: tf.int32}, {C: tf.int32, D: tf.int32})>

In [35]:
@tf.function
def filter_func(x):
    return x['C']>1

In [37]:
for j in ds.unbatch().filter(filter_func).take(6):
    print(j)

OrderedDict([('A', <tf.Tensor: shape=(), dtype=int32, numpy=5>), ('B', <tf.Tensor: shape=(), dtype=int32, numpy=5>), ('C', <tf.Tensor: shape=(), dtype=int32, numpy=5>), ('D', <tf.Tensor: shape=(), dtype=int32, numpy=5>)])
OrderedDict([('A', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('B', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('C', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('D', <tf.Tensor: shape=(), dtype=int32, numpy=2>)])
OrderedDict([('A', <tf.Tensor: shape=(), dtype=int32, numpy=6>), ('B', <tf.Tensor: shape=(), dtype=int32, numpy=6>), ('C', <tf.Tensor: shape=(), dtype=int32, numpy=6>), ('D', <tf.Tensor: shape=(), dtype=int32, numpy=6>)])
OrderedDict([('A', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('B', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('C', <tf.Tensor: shape=(), dtype=int32, numpy=2>), ('D', <tf.Tensor: shape=(), dtype=int32, numpy=2>)])
OrderedDict([('A', <tf.Tensor: shape=(), dtype=int32, numpy=6>), ('B', <tf.Tensor: shape=(), dtype=int32, numpy=

In [22]:
from tensorflow.python.data.ops import dataset_ops